name: englishword
description: "EnglishWord Client"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  cupertino_will_pop_scope: ^1.2.1 #pop scope (스와이프 백 제스쳐 지원)
  flutter_svg: ^2.0.5 # SVG 아이콘
  flutter_easyloading: ^3.0.5 # 로딩 UI 처리 관련
  flutter_animate: ^4.5.2 # 간편 애니메이션 메소드 지원

  just_audio: ^0.9.46 # 오디오 재생

  bounce_tapper: ^1.1.4 # 터치 효과
  gap: ^3.0.1 # 간격 위젯

  # DI
  get_it: ^7.2.0

  # 상태관리
  provider: ^6.0.5
  hooks_riverpod: "2.4.0"
  riverpod_annotation: "2.1.5"
  rxdart: ^0.27.7
  flutter_hooks: ^0.20.1

  # 라우팅
  go_router: ^13.1.0

  # 로컬 데이터베이스
  path_provider: ^2.1.1


  permission_handler: ^11.3.1 #각종 플랫폼 권한 허용 및 감지

  logger: ^2.5.0
  collection: ^1.18.0 # 콜렉션 타입 익스텐션 지원 메소드

  # 모델링
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1

  #데이터베이스
  floor: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.4.11
  go_router_builder: ^2.4.1
  riverpod_generator: "^2.3.2"
  riverpod_lint: ^2.1.0
  retrofit_generator: ^7.0.8
  freezed: ^2.4.3
  custom_lint: ^0.5.3
  analyzer: "6.4.1"
  floor_generator: ^1.5.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/raw/
    - assets/icons/

  fonts:
    - family: pretendard
      fonts:
        - asset: assets/fonts/pretendard/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/pretendard/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/pretendard/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/pretendard/Pretendard-Bold.otf
          weight: 800